#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# for detail see https://github.com/typicode/husky/issues/968#issuecomment-1176848345
if sh -c ": >/dev/tty" >/dev/null 2>/dev/null; then exec >/dev/tty 2>&1; fi

npx lint-staged --concurrent false
